FosterCommerce/dot-all-2022

composer.json, config/app.php, modules/fc/Fc.php, modules/fc/variables/FcVariable.php
Creates a business logic module ready to be used for adding custom functionality to the project
=> Add and install an empty business logic module

config/project/graphql/schemas/460addb0-40aa-48c7-ac8c-21f2f621ffbb.yaml, config/project/matrixBlockTypes/button--6f7d866f-f12e-4438-a53c-82110c2c13ab.yaml, config/project/project.yaml, package.json, yarn.lock
- Adds missing css-loader dependency
- Sets up the GQL schema
=> Add missing dependencies and set up GQL schema

.ddev/nginx_full/nginx-site.conf, config/general.php, src/layouts/default.vue, src/plugins/api.js
https://3.basecamp.com/3091851/buckets/27082467/messages/5236260230#__recording_5244922775
=> [WIP] Enable CSRF; more NGINX headers

src/store/cart.js
https://3.basecamp.com/3091851/buckets/27082467/todos/5160070248#__recording_5247057670
=> Cart Vuex state

src/components/base/BaseLoader.vue, src/components/cart/CartLineItem.vue, src/components/checkout/CheckoutCart.vue, src/components/checkout/CheckoutDiscount.vue, src/components/checkout/CheckoutLineItem.vue, src/components/checkout/CheckoutSummary.vue, src/layouts/default.vue, src/pages/cart.vue, src/pages/checkout.vue, src/plugins/api.js, src/store/cart.js
[🍰 Discount Coupon [S]](https://3.basecamp.com/3091851/buckets/27082467/todos/5167647277/edit?replace=true)
[🍰 Order Summary [M]](https://3.basecamp.com/3091851/buckets/27082467/todos/5167623554/edit?replace=true)
=> discount coupon and order summary

config/general.php
Reverts FosterCommerce/dot-all-2022#25
=> Revert "disble csrf again"

config/general.php, src/layouts/default.vue, src/plugins/api.js
Reverts FosterCommerce/dot-all-2022#24
=> Revert "fixed failed get request"

config/project/commerce/productTypes/catalog--8f9a9f81-cbc4-41eb-a70b-5eaeadea8840.yaml, config/project/project.yaml
- Reverts accidental project config changes
=> Revert accidental project config changes

src/components/views/PagesCollection.vue, src/queries/ProductsCatalog.gql
- Allow ordering by something in the GQL for collections queries, set it by newest in the pages
=> Fix ordering of products

config/project/entryTypes/general--6e4128ef-78da-40a5-aca7-b52de59fbc3c.yaml, config/project/project.yaml
- [🍰 Page Header](https://3.basecamp.com/3091851/buckets/27082467/todos/5181434309)
=> Remove header image field from general pages

src/queries/EntriesPages.gql
- Removes a query for a field that was removed from general pages
=> Remove query for removed field

src/components/global/Pagination.vue, src/components/views/PagesGeneral.vue, src/layouts/default.vue
- Fix pagination bug when number of pages is less than 7 but greater than 3
- Fix async/await issues in default.vue
- Fix syntax inconsistencies and/or style guide violations in default.vue and PagesGeneral.vue
=> Make it better

nuxt.config.js, src/layouts/default.vue, src/queries/SEOMatic.gql
- [🛠 Ensure SEOMatic data is output to HTML](https://3.basecamp.com/3091851/buckets/27082467/todos/5261158687)
=> SEOmatic data to HTML

modules/fc/Fc.php, modules/fc/controllers/AddressesController.php, modules/fc/services/AddressesService.php, src/components/checkout/CheckoutAddressFields.vue, src/components/checkout/CheckoutStepAddress.vue, src/plugins/api.js, src/store/cart.js, src/store/checkout.js, src/store/user.js
- https://3.basecamp.com/3091851/buckets/27082467/todos/5293494026
- https://3.basecamp.com/3091851/buckets/27082467/todos/5293432633
- https://3.basecamp.com/3091851/buckets/27082467/todos/5167820360
- https://3.basecamp.com/3091851/buckets/27082467/todos/5167941343
=> Checkout Shipping Addresses

src/store/checkout.js
- https://3.basecamp.com/3091851/buckets/27082467/todos/5167941343
=> Bugfix: prevented attempting to retrieve null shipping address ID.

src/components/checkout/CheckoutCart.vue, src/components/checkout/CheckoutLineItem.vue, src/pages/catalog/index.vue
- Matches checkout cart line items to cart line items output (color and size of selected variant)
=> Matching checkout line item to cart line item

config/general.php
- Adds webroot alias to config
=> Adding webroot alias to prevent cache clear error in CP resources

src/components/checkout/CheckoutStepPayment.vue, src/plugins/api.js
- [🛠 Capture and properly format payment details to prepare for Stripe API](https://3.basecamp.com/3091851/buckets/27082467/todos/5329937012)
=> Format payment info for Stripe

package.json, src/components/checkout/CheckoutStepPayment.vue, src/plugins/api.js, yarn.lock
=> Get Stripe gateway working

src/components/checkout/CheckoutStepPayment.vue, src/plugins/api.js
- [🛠 API Endpoint for Stripe Payment Gateway](https://3.basecamp.com/3091851/buckets/27082467/todos/5167855821#__recording_5340789719)
=> Reset error messages on change in Stripe payment

modules/fc/Fc.php, modules/fc/controllers/PaymentsController.php, src/components/checkout/CheckoutStepPayment.vue
- [🛠 API Endpoint for PayPal Payment Gateway](https://3.basecamp.com/3091851/buckets/27082467/todos/5167867382)
=> PayPal gateway

composer.json, composer.lock, config/project/commerce/gateways/manual--148bf625-3ed8-48e1-9a43-70fc218ce67c.yaml, config/project/project.yaml, modules/fc/Fc.php, modules/fc/controllers/PaymentsController.php, modules/fc/services/CriticalDataService.php, src/components/checkout/CheckoutStepPayment.vue, src/plugins/api.js
- [🛠 API Endpoint for Manual Payment Gateway](https://3.basecamp.com/3091851/buckets/27082467/todos/5167873210)
=> Manual gateway

src/components/checkout/CheckoutStepPayment.vue
=> Move PayPal button

src/components/checkout/CheckoutStepPayment.vue
- Adds the mailing address to the manual payment option in checkout
=> Add mailing info to manual gateway on payment checkout step

config/project/commerce/gateways/paypal--56fd568a-e1bd-46d2-af2f-8a5b610e47bf.yaml, config/project/project.yaml
- https://3.basecamp.com/3091851/buckets/27082467/todos/5338550293#__recording_5363297912
=> Hopefully fix 500 on prod for PayPal
